events {
    worker_connections 1024;
}

http {
    # Basic types
    types {
        text/html html;
        text/css css;
        application/javascript js;
        application/json json;
        image/png png;
        image/jpeg jpg jpeg;
    }
    default_type application/octet-stream;

    # Load lua module
    # Load lua module
    lua_package_path "/usr/local/openresty/lualib/?.lua;/usr/local/openresty/lualib/resty/?.lua;;";

    # Include server configurations
    include /etc/nginx/conf.d/*.conf;
}
