events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    # Load lua module
    lua_package_path "/usr/local/openresty/lualib/?.lua;/usr/local/openresty/lualib/resty/?.lua;;";

    # Include server configurations
    include /etc/nginx/conf.d/*.conf;
}
