export const getAvailableFonts = async () => {
    const fontList = [
        "Agency FB",
        "American Typewriter",
        "Andale Mono",
        "Arabic Typesetting",
        "Arial",
        "Arial Black",
        "Arial Narrow",
        "Arial Rounded MT Bold",
        "Arial Unicode MS",
        "ARNO PRO",
        "AvantGarde Bk BT",
        "Avenir",
        "Avenir Next",
        "Avenir Next Condensed",
        "Bahnschrift",
        "BankGothic Md BT",
        "Baskerville",
        "Batang",
        "Big Caslon",
        "Bitstream Vera Sans Mono",
        "Bodoni 72",
        "Bodoni 72 Oldstyle",
        "Bodoni 72 Smallcaps",
        "Bradley Hand",
        "Brush Script MT",
        "Calibri",
        "Cambria",
        "Cambria Math",
        "Candara",
        "Century",
        "Century Gothic",
        "Chalkboard",
        "Chalkboard SE",
        "Chalkduster",
        "Charter",
        "Clarendon",
        "Cochin",
        "Comic Sans MS",
        "Consolas",
        "Constantia",
        "Copperplate",
        "Corbel",
        "Courier",
        "Courier New",
        "DIN Alternate",
        "DIN Condensed",
        "Didot",
        "Ebrima",
        "EUROSTILE",
        "Franklin Gothic",
        "Franklin Gothic Medium",
        "Futura",
        "Futura Bk BT",
        "Futura Md BT",
        "Gabriola",
        "Gadugi",
        "Geneva",
        "Georgia",
        "Gill Sans",
        "GOTHAM",
        "Haettenschweiler",
        "HELV",
        "Helvetica",
        "Helvetica Neue",
        "Herculanum",
        "Hoefler Text",
        "HoloLens MDL2 Assets",
        "Humanst521 BT",
        "Impact",
        "Ink Free",
        "Javanese Text",
        "Leelawadee",
        "Leelawadee UI",
        "Letter Gothic",
        "Levenim MT",
        "Lucida Bright",
        "Lucida Console",
        "Lucida Grande",
        "Lucida Sans",
        "Lucida Sans Unicode",
        "Luminari",
        "Malgun Gothic",
        "Marker Felt",
        "Marlett",
        "Meiryo UI",
        "Menlo",
        "Microsoft Himalaya",
        "Microsoft JhengHei",
        "Microsoft New Tai Lue",
        "Microsoft PhagsPa",
        "Microsoft Sans Serif",
        "Microsoft Tai Le",
        "Microsoft Uighur",
        "Microsoft YaHei",
        "Microsoft Yi Baiti",
        "MingLiU-ExtB",
        "Minion Pro",
        "Monaco",
        "Mongolian Baiti",
        "Monotype Corsiva",
        "MS Gothic",
        "MS Mincho",
        "MS Outlook",
        "MS Reference Specialty",
        "MS UI Gothic",
        "MT Extra",
        "MV Boli",
        "Myanmar Text",
        "MYRIAD PRO",
        "Nirmala UI",
        "Noteworthy",
        "Optima",
        "Palatino",
        "Palatino Linotype",
        "Papyrus",
        "Phosphate",
        "PMingLiU",
        "Pristina",
        "Rockwell",
        "sans-serif-thin",
        "Savoye LET",
        "SCRIPTINA",
        "Segoe MDL2 Assets",
        "Segoe Print",
        "Segoe Script",
        "Segoe UI",
        "Segoe UI Emoji",
        "Segoe UI Historic",
        "Segoe UI Light",
        "Segoe UI Symbol",
        "Serifa",
        "SignPainter",
        "SimHei",
        "SimSun",
        "Sitka",
        "Skia",
        "Small Fonts",
        "Snell Roundhand",
        "Staccato222 BT",
        "Sylfaen",
        "Symbol",
        "Tahoma",
        "Times",
        "Times New Roman",
        "TRAJAN PRO",
        "Trattatello",
        "Trebuchet MS",
        "Univers CE 55 Medium",
        "Verdana",
        "Vrinda",
        "Webdings",
        "Wingdings",
        "Yu Gothic",
        "Zapfino",
        "ZWAdobeF"
    ];

    const availableFonts = new Set();
    
    await document.fonts.ready;

    fontList.sort().forEach((font) => {
        if (document.fonts.check(`48px '${font}'`)) {
            availableFonts.add(font);
        }
    });

    return Array.from(availableFonts);
}